[workspace]
resolver = "2"
members = ["cli", "sp1-program", "executor", "verifier", "sdk"]

[workspace.dependencies]
bincode = {version = "2", features = ["serde"]}
lazy_static = {version = "1.5.0", features = ["spin_no_std"]}
num-bigint = {version = "0.4", default-features = false}
p3-baby-bear = {version = "0.2.2-succinct"}
p3-field = {version = "0.2.2-succinct"}
p3-poseidon2 = {version = "0.2.2-succinct"}
p3-symmetric = {version = "0.2.2-succinct"}
p3-util = {version = "0.2.2-succinct"}
rstest = {version = "0.25"}
serde = {version = "1", default-features = false}
sha2 = {version = "0.10", default-features = false}
sp1-build = {version = "4.2.0"}
sp1-core-executor = {version = "4.2.0", default-features = false}
sp1-derive = {version = "4.2.0", default-features = false}
sp1-primitives = {version = "4.2.0", default-features = false}
sp1-prover = {version = "4.2.0", default-features = false}
sp1-recursion-circuit = {version = "4.2.0", default-features = false}
sp1-recursion-compiler = {version = "4.2.0", default-features = false}
sp1-recursion-core = {version = "4.2.0", default-features = false}
sp1-sdk = {version = "4.2.0", default-features = false}
sp1-stark = {version = "4.2.0", default-features = false}
sp1-zkvm = {version = "4.2.0"}
