[package]
name = "sp1-program"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
sp1-zkvm = {workspace = true}
sha2 = { git = "https://github.com/succinctbot/RustCrypto-hashes.git" }